name: Generate Pac-Man contribution graph

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate pacman-contribution-graph.svg
        uses: abozanona/pacman-contribution-graph@master
        with:
          github_user_name: JaScriptor
          output: svg
          theme: github
          platform: github
          speed: 2
          sound: false

      - name: Commit & push output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -B output
          git add -A
          git commit -m "Generate pacman contribution graph [skip ci]" || echo "No changes to commit"
          git push -u origin output --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
